name: Build Letter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "19 5 * * 3"

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./Brief/
          root_file: Brief.tex

      - name: Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./Brief/Brief.pdf
